export const PROVIDER_DEFAULTS: Record<string, Record<string, any>> = {
  openai: {
    name: '',
    api_key: '',
    model: 'gpt-4o',
    sampling_preset_name: '',
    extra_params: '{}',
    max_tokens: -1,
    temperature: 0.7,
    top_p: 1.0,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_completion_tokens: 0,
    seed: 0,
    response_format: '',
    reasoning_effort: '',
    top_k: 0,
    top_a: 0,
    min_p: 0,
    repetition_penalty: 0,
    stop_tokens: '',
    voice: '',
    speed: 1.0,
    format: 'mp3',
  },
  openaicompatible: {
    name: '',
    base_url: 'http://localhost:8080/v1',
    api_key: '',
    model: '',
    sampling_preset_name: '',
    extra_params: '{}',
    max_tokens: -1,
    temperature: 0.7,
    top_p: 1.0,
    top_k: 0,
    top_a: 0,
    min_p: 0,
    repetition_penalty: 0,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_completion_tokens: 0,
    seed: 0,
    response_format: '',
    stop_tokens: '',
  },
  openrouter: {
    name: '',
    api_key: '',
    model: '',
    sampling_preset_name: '',
    extra_params: '{}',
    max_tokens: -1,
    temperature: 0.7,
    top_p: 1.0,
    top_k: 0,
    top_a: 0,
    min_p: 0,
    repetition_penalty: 0,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_completion_tokens: 0,
    seed: 0,
    response_format: '',
    stop_tokens: '',
    voice: '',
    speed: 1.0,
    format: '',
    image_aspect_ratio: '',
    image_size: '',
  },
  elevenlabs: {
    name: '',
    api_key: '',
    voice_id: '',
    model_id: '',
    stability: 0.5,
    similarity_boost: 0.75,
    style: 0,
    speaker_boost: 0,
  },
  harmonyspeech: {
    name: '',
    endpoint: '',
    model: '',
    voice_config_file: '',
    format: 'wav',
    sample_rate: 22050,
    stream: 0,
  },
  kindroid: {
    name: '',
    api_key: '',
    kindroid_id: '',
  },
  kajiwoto: {
    name: '',
    username: '',
    password: '',
    room_url: '',
  },
  characterai: {
    name: '',
    api_token: '',
    chatroom_url: '',
  },
  localai: {
    name: '',
    model: '',
  },
  mistral: {
    name: '',
    api_key: '',
  },
  ollama: {
    name: '',
    base_url: 'http://localhost:11434',
    model: '',
  },
  comfyui: {
    name: '',
    base_url: 'http://localhost:8188',
    api_key: '',
    workflow_profiles: '',
  },
  google: {
    name: '',
    api_key: '',
    model: 'gemini-2.5-flash',
    sampling_preset_name: '',
    extra_params: '{}',
    max_output_tokens: 0,
    temperature: 0.7,
    top_p: 1.0,
    top_k: 0,
    stop_tokens: '',
    response_mime_type: '',
    number_of_images: 1,
    aspect_ratio: '',
  },
  xai: {
    name: '',
    api_key: '',
    model: 'grok-3',
    sampling_preset_name: '',
    extra_params: '{}',
    max_tokens: -1,
    temperature: 0.7,
    top_p: 1.0,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_completion_tokens: 0,
    seed: 0,
    response_format: '',
    reasoning_effort: '',
    stop_tokens: '',
    n: 1,
    image_aspect_ratio: '',
    image_resolution: '',
  },
  anthropic: {
    name: '',
    api_key: '',
    model: 'claude-sonnet-4-20250514',
    sampling_preset_name: '',
    extra_params: '{}',
    max_tokens: 4096,
    temperature: 0.7,
    top_p: 1.0,
    top_k: 0,
    stop_sequences: '',
  },
};

export const MODULE_DEFAULTS: Record<string, Record<string, any>> = {
  backend: {},
  cognition: { max_cognition_events: 10, generate_expressions: 0 },
  movement: { startup_sync_timeout: 0, execution_threshold: 0 },
  rag: { embedding_concurrency: 0 },
  tts: { output_type: '', words_to_replace: '', vocalize_nonverbal: 0 },
  stt: { main_stream_time_millis: 2000, transition_stream_time_millis: 1000, max_buffer_count: 5 },
  vision: { resolution_width: 1024, resolution_height: 1024 },
  imagination: {},
};